## Data Cleaning — 20 Questions

In [4]:
import pandas as pd

df=pd.read_csv("C:\\Users\\vaish\\Downloads\\matplotlib_messy_sales_2000.csv")

In [94]:
# 1 Column Names
# Display all column names. Identify columns having leading/trailing spaces and
# rename all columns into a consistent snake_case format.
df.columns

df.columns=df.columns.str.strip()
df.columns=df.columns.str.replace(" ","_").str.lower()
df.columns

Index(['customer_id', '_order_date_', 'city', 'product_category',
       'customer_segment', 'gender', 'sales_channel', 'age', 'units_sold',
       'unit_price', 'discount_%', 'customer_rating', 'is_active', 'returned',
       'payment_method', 'gross_sales', 'discount_amount', 'revenue', 'cost',
       'profit'],
      dtype='object')

In [96]:
# 2. Duplicate Records
# Find the number of duplicate rows. Remove the duplicate records and verify that no
# duplicates remain.
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

In [98]:
# 3. Missing Values
# Display the missing-value count and missing-value percentage for every column.
df.columns.isnull().sum()
df.columns.isnull().sum()/100

0.0

In [100]:
# 4. Missing Categorical Values
# Handle missing values in city, product_category, and payment_method using an
# appropriate strategy.\
df["city"].fillna(method="ffill")
df.head(2)
df["product_category"].fillna(method="ffill")
df["payment_method"].fillna(method="ffill")

C:\Users\vaish\AppData\Local\Temp\ipykernel_1684\2258461541.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["city"].fillna(method="ffill")
C:\Users\vaish\AppData\Local\Temp\ipykernel_1684\2258461541.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["product_category"].fillna(method="ffill")
C:\Users\vaish\AppData\Local\Temp\ipykernel_1684\2258461541.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["payment_method"].fillna(method="ffill")

0               UPI
1              Cash
2        Debit Card
3       Net Banking
4       Net Banking
           ...
2015            UPI
2016           Cash
2017            UPI
2018            UPI
2019    Credit Card
Name: payment_method, Length: 2000, dtype: object

In [102]:
# 5. Missing Numerical Values
# Handle missing values in age, unit_price, discount_pct, customer_rating, and
# revenue. Explain why you selected mean, median, or another method.
col=["age","unit_price","discount_%","customer_rating","revenue"]

for i in col:
    df[i]=pd.to_numeric(df[i],errors="coerce")

age_mean=df["age"].median()
df["age"]=df["age"].fillna(age_mean)

price_median=df["unit_price"].median()
df["unit_price"]=df["unit_price"].fillna(price_median)

diccount_med=df["discount_%"].median()
df["discount_%"]=df["discount_%"].fillna(diccount_med)

rating_median=df["customer_rating"].median()
df["customer_rating"]=df["customer_rating"].fillna(rating_median)

revenue_median=df["revenue"].median()
df["revenue"]=df["revenue"].fillna(revenue_median)

In [120]:
# 6. Date Cleaning
# Convert order_date into a proper datetime format. Identify invalid date values and
# handle them appropriately.
df["_order_date_"]=pd.to_datetime(df["_order_date_"],errors="coerce")
df["_order_date_"].isnull().sum()
df["_order_date_"]=df["_order_date_"].fillna(method="ffill")

C:\Users\vaish\AppData\Local\Temp\ipykernel_1684\1236567229.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["_order_date_"]=df["_order_date_"].fillna(method="ffill")

In [122]:
df["_order_date_"].isnull().sum()

0

In [126]:
# 7. Age Cleaning
# The age column contains values such as 25 years, 30 yrs, 45Y, and N/A. Extract the
# numerical age and convert the column into a numeric datatype.
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df["age"]

0       36.0
1       38.0
2       65.0
3       34.0
4       41.0
        ...
2015    24.0
2016    44.0
2017    56.0
2018    41.0
2019    68.0
Name: age, Length: 2000, dtype: float64

In [130]:
# 8. Age Outliers
# Identify unrealistic ages such as 120, 150, and 200. Detect them using the IQR
# method and handle them appropriately.
q1=df["age"].quantile(0.25)
q3=df["age"].quantile(0.75)

IQR=q3-q1

filtered=df[(df["age"]>=q1-1.5*IQR) & (df["age"]<=q3+1.5*IQR)]
filtered

,customer_id,_order_date_,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.590000,88698.45,60768.14
1,CUST01103,2025-10-22,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.680000,61426.31,13631.37
2,CUST00690,2025-04-24,Delhi,Home & Kitchen,Regular,Male,Retail,65.0,2,24579.97,36.22,4.5,1,0,Debit Card,49159.94,17805.73,31354.210000,24948.21,6406.00
3,CUST00215,2025-05-17,Chennai,Electronics,Regular,Male,Corporate,34.0,9,6240.13,20.44,3.9,1,0,Net Banking,56161.17,11479.34,91355.371818,26470.33,18211.50
4,CUST01270,2025-08-30,Delhi,Clothing,Budget,Female,Corporate,41.0,1,23491.23,10.48,3.7,1,0,Net Banking,23491.23,2461.88,21029.350000,12312.38,8716.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CUST00043,2025-12-17,Pune,Sports,Premium,Male,Retail,24.0,10,9181.27,18.05,3.7,1,0,UPI,91812.70,16572.19,75240.510000,39994.75,35245.76
2016,CUST00602,2025-12-22,Pune,Sports,Regular,Female,Retail,44.0,9,6947.94,32.93,1.5,1,0,Cash,62531.46,20591.61,41939.850000,33246.33,8693.52
2017,CUST01708,2025-05-28,Hyderabad,Home & Kitchen,Premium,Male,Retail,56.0,5,5393.37,25.19,3.4,1,0,UPI,26966.85,6792.95,20173.900000,13654.93,6518.97
2018,CUST00614,2025-08-27,Chennai,Sports,Premium,Male,Online,41.0,7,10803.59,0.50,5.0,1,0,UPI,75625.13,378.13,75247.000000,46822.20,28424.80
2019,CUST01948,2025-12-23,Pune,Beauty,Regular,Female,Retail,68.0,12,18336.56,23.29,4.7,1,0,Credit Card,220038.72,51247.02,168791.700000,107140.44,61651.26

In [134]:
# 9. Unit Price Cleaning
# The unit_price column contains values such as ₹15000, $20000, 25000 INR, and 10k.
# Convert all valid values into a single numeric format.
df["unit_price"]=pd.to_numeric(df["unit_price"],errors="coerce")
df["unit_price"]

0       24235.73
1       16789.55
2       24579.97
3        6240.13
4       23491.23
          ...
2015     9181.27
2016     6947.94
2017     5393.37
2018    10803.59
2019    18336.56
Name: unit_price, Length: 2000, dtype: float64

In [144]:
# 10. Unit Price Outliers
# Detect extreme unit_price values using the IQR method. Compare the number of
# outliers before and after treatment.
q1=df["unit_price"].quantile(0.25)
q3=df["unit_price"].quantile(0.75)
IQR=q3-q1
extreme=df[(df["unit_price"]>=q1-1.5*IQR) & (df["unit_price"]<=q3+1.5*IQR)]
extreme

,customer_id,_order_date_,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.590000,88698.45,60768.14
1,CUST01103,2025-10-22,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.680000,61426.31,13631.37
2,CUST00690,2025-04-24,Delhi,Home & Kitchen,Regular,Male,Retail,65.0,2,24579.97,36.22,4.5,1,0,Debit Card,49159.94,17805.73,31354.210000,24948.21,6406.00
3,CUST00215,2025-05-17,Chennai,Electronics,Regular,Male,Corporate,34.0,9,6240.13,20.44,3.9,1,0,Net Banking,56161.17,11479.34,91355.371818,26470.33,18211.50
4,CUST01270,2025-08-30,Delhi,Clothing,Budget,Female,Corporate,41.0,1,23491.23,10.48,3.7,1,0,Net Banking,23491.23,2461.88,21029.350000,12312.38,8716.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CUST00043,2025-12-17,Pune,Sports,Premium,Male,Retail,24.0,10,9181.27,18.05,3.7,1,0,UPI,91812.70,16572.19,75240.510000,39994.75,35245.76
2016,CUST00602,2025-12-22,Pune,Sports,Regular,Female,Retail,44.0,9,6947.94,32.93,1.5,1,0,Cash,62531.46,20591.61,41939.850000,33246.33,8693.52
2017,CUST01708,2025-05-28,Hyderabad,Home & Kitchen,Premium,Male,Retail,56.0,5,5393.37,25.19,3.4,1,0,UPI,26966.85,6792.95,20173.900000,13654.93,6518.97
2018,CUST00614,2025-08-27,Chennai,Sports,Premium,Male,Online,41.0,7,10803.59,0.50,5.0,1,0,UPI,75625.13,378.13,75247.000000,46822.20,28424.80
2019,CUST01948,2025-12-23,Pune,Beauty,Regular,Female,Retail,68.0,12,18336.56,23.29,4.7,1,0,Credit Card,220038.72,51247.02,168791.700000,107140.44,61651.26

In [148]:
# 11. Units Sold Cleaning
# Clean values such as 5 units, 10 pcs, twenty, N/A, and 3 and convert the column into
# a numeric datatype.
df["units_sold"]=pd.to_numeric(df["units_sold"],errors="coerce")
df["units_sold"]

0        8.0
1        5.0
2        2.0
3        9.0
4        1.0
        ...
2015    10.0
2016     9.0
2017     5.0
2018     7.0
2019    12.0
Name: units_sold, Length: 2000, dtype: float64

In [156]:
# 12. Discount Cleaning
# Clean values such as 10%, 20 percent, 5 %, none, and N/A. Convert the final
# discount_pct column into numeric values between 0 and 100.
df["discount_amount"]=pd.to_numeric(df["discount_amount"],errors="coerce")
df["discount_amount"]

0       44419.25
1        8890.07
2       17805.73
3       11479.34
4        2461.88
          ...
2015    16572.19
2016    20591.61
2017     6792.95
2018      378.13
2019    51247.02
Name: discount_amount, Length: 2000, dtype: float64

In [160]:
# 13. Discount Outliers
# Identify invalid discount values such as 75, 90, and 120. Determine which values are
# unrealistic and handle them.
q1=df["discount_amount"].quantile(0.25)
q3=df["discount_amount"].quantile(0.75)
IQR=q3-q1

invalid=df[(df["discount_amount"]>=q1-1.5*IQR) &(df["discount_amount"]<=q3+1.5*IQR)]
df["discount_amount"]

0       44419.25
1        8890.07
2       17805.73
3       11479.34
4        2461.88
          ...
2015    16572.19
2016    20591.61
2017     6792.95
2018      378.13
2019    51247.02
Name: discount_amount, Length: 2000, dtype: float64

In [172]:
# 14. City Standardization
# Standardize inconsistent city values such as:
# o Mumbai
# o mumbai
# o MUMBAI
# o Mumbai
# o Bangalore
# o bangalore
# o Hyderbad

df["city"].unique()
df["city"]=df["city"].str.strip()
df["city"]=df["city"].replace({"mumbai":"Mumbai","MUMBAI":"Mumbai","DELHI":"Delhi",
                              "delhi":"Delhi","Hyderbad":"Hyderabad","bangalore":"Bengaluru"})

In [174]:
df["city"].unique()

array(['Mumbai', 'Delhi', 'Chennai', 'Hyderabad', 'Pune', 'Bengaluru',
       nan], dtype=object)

In [188]:
# 15. Product Category Cleaning
# Standardize values such as Electronics, electronics, ELECTRONICS, Home and Kitchen,
# home & kitchen, and Beauty .
df["product_category"].unique()
df["product_category"]=df["product_category"].str.strip().replace(
    {
        "Home and Kitchen":"Home & Kitchen",
        'home & kitchen':'Home & Kitchen',
        'ELECTRONICS':'Electronics',
        'electronics':'Electronics'
    }
)
df["product_category"].unique()

array(['Clothing', 'Home & Kitchen', 'Electronics', 'Sports', 'Beauty',
       nan], dtype=object)

In [205]:
# 16. Gender Cleaning
# Standardize values such as Male, male, Male, FEMALE, female , M, and F into
# consistent categories.

df["gender"]=df["gender"].str.strip().replace({
    "male":"Male",
    "M":"Male",
    "female":"Female",
    "F":"Female",
    "FEMALE":"Female"
})
df["gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [215]:
# 17. Customer Segment Cleaning
# Identify invalid values such as Prem, Reg, VIP, and Unknown. Map valid variations to
# the correct categories and decide how to handle invalid categories.
df['customer_segment'].unique()
df['customer_segment']=df['customer_segment'].str.strip().replace({
    'premium':'Premium',
    'Prem':'Premium',
    'Reg':'Regular',
    
})
df['customer_segment'].unique()

array(['Premium', 'Regular', 'Budget'], dtype=object)

In [221]:
# 18. Binary Column Cleaning
# Clean is_active and returned, where values contain combinations of:
# o 0/1
# o Yes/No
# o Y/N
# o Active/Inactive
# o Returned/Not Returned
# Convert both columns into a consistent 0/1 binary format.
df["is_active"]=df["is_active"].str.strip().replace({
    'Active':'1',
    'Y':'1',
    'Yes':'1',
    'Inactive':'0',
    'N':'0',
    'No':'0'
})

In [223]:
df["is_active"].unique()

array(['1', '0'], dtype=object)

In [225]:
# 19. Data-Type Validation
# After cleaning, display df.info() and verify that:
# o Dates are datetime
# o Numerical columns are numeric
# o Binary columns contain only 0 and 1
# o Categorical columns contain clean strings
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2019
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2000 non-null   object
 1   _order_date_      2000 non-null   datetime64[ns]
 2   city              1975 non-null   object
 3   product_category  1976 non-null   object
 4   customer_segment  2000 non-null   object
 5   gender            2000 non-null   object
 6   sales_channel     2000 non-null   object
 7   age               2000 non-null   float64
 8   units_sold        1983 non-null   float64
 9   unit_price        2000 non-null   float64
 10  discount_%        2000 non-null   float64
 11  customer_rating   2000 non-null   float64
 12  is_active         2000 non-null   object
 13  returned          2000 non-null   object
 14  payment_method    1975 non-null   object
 15  gross_sales       2000 non-null   float64
 16  discount_amount   2000 non-null   float64
 17  revenue           2000 non-null   float64
 18  cost              2000 non-null   float64
 19  profit            2000 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(9)
memory usage: 328.1+ KB

In [284]:
# 20. Final Data Quality Check — Hardest
# Perform a complete final audit of the cleaned dataset:
# o Check duplicate rows
# o Check missing values
# o Check invalid dates
# o Check numerical columns
# o Check outliers
# o Check categorical inconsistencies
# o Check binary values
# o Check datatypes
# o Verify that Revenue, Cost, and Profit are logically consistent

df.duplicated().sum()

df.isnull().sum()

df["_order_date_"].isnull().sum()

num_cols = [
    "age",
    "unit_price",
    "discount_%",
    "customer_rating",
    "units_sold",
    "revenue",
    "cost",
    "profit"
]
df[num_cols].describe()

for i in num_cols:
    q1=df[i].quantile(0.25)
    q3=df[i].quantile(0.75)
    IQR=q3-q1
    lb=q1-1.5*IQR
    ub=q3+1.5*IQR
    outliers=df[(df[i]<lb) | (df[i]>=ub)]
    print(outliers)

cat_cols = [
    "city",
    "product_category",
    "customer_segment",
    "gender",
    "sales_channel",
    "payment_method"
]
for i in cat_cols:
    df[i].unique()

bin_col=["is_active","returned"]
for i in bin_cols:
    df[i].unique()

df.dtypes

     customer_id _order_date_       city product_category customer_segment  \
193    CUST01152   2025-08-17  Hyderabad      Electronics          Premium
256    CUST01689   2025-03-26     Mumbai         Clothing           Budget
323    CUST00564   2025-05-01     Mumbai         Clothing           Budget
329    CUST00905   2025-01-04      Delhi      Electronics          Premium
467    CUST01798   2025-01-23     Mumbai           Beauty          Regular
534    CUST01658   2025-03-29       Pune   Home & Kitchen          Regular
647    CUST00838   2025-10-26    Chennai      Electronics           Budget
777    CUST01245   2025-04-17     Mumbai           Beauty          Premium
869    CUST01120   2025-10-22      Delhi           Beauty           Budget
991    CUST01989   2025-09-08     Mumbai      Electronics          Regular
1023   CUST01998   2025-08-15     Mumbai           Sports          Regular
1532   CUST00886   2025-02-09     Mumbai           Sports          Premium
1731   CUST00783   2025-05-24      Delhi      Electronics           Budget
2000   CUST01513   2025-09-07       Pune         Clothing          Regular

      gender sales_channel    age  units_sold  unit_price  discount_%  \
193   Female     Corporate  150.0        10.0     7888.62        2.94
256     Male     Corporate  120.0         2.0    23011.77       35.61
323   Female        Retail  120.0        13.0     5388.98       36.86
329   Female     Corporate  200.0         5.0     1420.73       18.35
467     Male        Online  120.0        14.0    11747.60        3.50
534     Male     Corporate  200.0         3.0    22272.83       24.35
647   Female        Retail  120.0         9.0    13318.51       22.99
777   Female        Online  150.0        14.0    10252.23        9.41
869     Male        Retail  150.0         9.0    19580.66       17.37
991     Male     Corporate  150.0         6.0     2945.85       11.78
1023    Male        Online  120.0        12.0    14713.78       39.96
1532  Female        Retail  150.0         6.0     5779.57       33.86
1731  Female     Corporate  120.0         9.0    11462.24       34.44
2000    Male     Corporate  120.0        11.0    20446.77       30.73

      customer_rating is_active returned payment_method  gross_sales  \
193               1.8         1        1    Net Banking     78886.20
256               3.5         1        0    Net Banking     46023.54
323               4.1         1        0    Credit Card     70056.74
329               1.6         0        1           Cash      7103.65
467               3.6         0        0    Credit Card    164466.40
534               1.5         0        0     Debit Card     66818.49
647               3.4         0        0            UPI    119866.59
777               4.5         1        1    Credit Card    143531.22
869               4.1         1        0            UPI    176225.94
991               3.5         0        0    Credit Card     17675.10
1023              4.9         1        0    Net Banking    176565.36
1532              1.6         1        0           Cash     34677.42
1731              1.4         0        0     Debit Card    103160.16
2000              2.8         1        0    Credit Card    224914.47

      discount_amount    revenue       cost    profit
193           2319.25   76566.95   61088.36  15478.59
256          16388.98   29634.56   21762.78   7871.78
323          25822.91   44233.83   22681.23  21552.60
329           1303.52    5800.13    3877.60   1922.53
467           5756.32  158710.08  101891.62  56818.46
534          16270.30   50548.19   40449.06  10099.13
647          27557.33   92309.26   58284.17  34025.09
777          13506.29  130024.93   77393.39  52631.54
869          30610.45  145615.49   76225.06  69390.43
991           2082.13   15592.97   10349.59   5243.38
1023         70555.52  106009.84   70652.27  35357.57
1532         11741.77   22935.65   17631.99   5303.66
1731         35528.36   67631.80   40478.53  27153.27
2000         69116.22  155798.25   83293.18  72505.07
     customer_id _order_date_       city product_category customer_segment  \
8      CUST00927   2025-03-22     Mumbai         Clothing          Regular
187    CUST00750   2025-06-02  Hyderabad           Beauty          Premium
288    CUST01079   2025-05-05  Hyderabad   Home & Kitchen          Regular
350    CUST01970   2025-08-02  Hyderabad   Home & Kitchen           Budget
358    CUST00292   2025-03-23  Bengaluru           Sports          Regular
446    CUST01906   2025-06-06       Pune           Beauty          Regular
482    CUST00236   2025-12-06  Bengaluru           Sports          Regular
544    CUST01338   2025-01-25  Bengaluru           Sports          Regular
750    CUST01735   2025-11-09    Chennai   Home & Kitchen          Premium
867    CUST01522   2025-03-04     Mumbai   Home & Kitchen          Premium
932    CUST01389   2025-02-02      Delhi           Beauty          Regular
1029   CUST01576   2025-10-13    Chennai           Sports          Regular
1060   CUST00976   2025-01-28     Mumbai           Beauty          Regular
1337   CUST00895   2025-06-01      Delhi   Home & Kitchen           Budget
1578   CUST01777   2025-09-24      Delhi         Clothing          Premium

      gender sales_channel   age  units_sold  unit_price  discount_%  \
8     Female        Retail  61.0        12.0    250000.0       35.94
187     Male     Corporate  33.0        13.0    150000.0       35.61
288   Female     Corporate  24.0         8.0    150000.0       14.16
350     Male     Corporate  39.0         5.0    250000.0       32.94
358     Male     Corporate  45.0         4.0    150000.0       33.74
446     Male        Online  27.0         1.0    250000.0       29.97
482   Female        Online  60.0         9.0    100000.0        1.96
544     Male        Retail  56.0         3.0    100000.0       25.92
750   Female        Online  40.0         5.0    250000.0       16.55
867     Male     Corporate  64.0         8.0    150000.0        3.28
932   Female        Retail  69.0         5.0    150000.0       10.00
1029  Female        Retail  43.0        11.0    100000.0        9.36
1060  Female        Online  19.0        12.0    100000.0       36.04
1337  Female        Online  44.0         4.0    100000.0       13.88
1578    Male          Corp  30.0         4.0    250000.0       20.48

      customer_rating is_active returned payment_method  gross_sales  \
8                 1.6         1        1    Net Banking    213087.24
187               2.9         1        0            UPI    356738.72
288               1.1         1        0     Debit Card    212019.92
350               4.6         1        0     Debit Card    144782.35
358               3.4         1        0    Net Banking     40630.84
446               1.1         1        0           Cash      2513.91
482               3.3         1        0           Cash      5524.74
544               2.9         0        0    Net Banking     54311.25
750               1.4         1        1     Debit Card    107653.75
867               3.6         1        0            UPI    182013.52
932               1.1         1        1    Credit Card    102090.00
1029              4.3         1        0    Credit Card    152626.54
1060              4.6         1        0     Debit Card      5106.00
1337              4.1         1        0    Net Banking     40341.68
1578              3.3         0        0            UPI     73934.96

      discount_amount    revenue       cost    profit
8            76583.55  136503.69   92634.53  43869.16
187         127034.66  229704.06  176479.19  53224.87
288          30022.02  181997.90  132863.01  49134.89
350          47691.31   97091.04   53185.01  43906.03
358          13708.85   26921.99   21214.16   5707.83
446            753.42    1760.49     890.46    870.03
482            108.28    5416.46    4384.53   1031.93
544          14077.48   40233.77   30491.69   9742.08
750          17816.70   89837.05   56512.71  33324.34
867           5970.04  176043.48   95232.28  80811.20
932          10209.00   91881.00   71087.27  20793.73
1029         14285.84  138340.70   87115.83  51224.87
1060          1840.20    3265.80    2159.20   1106.60
1337          5599.43   34742.25   19263.31  15478.94
1578         15141.88   58793.08   30844.03  27949.05
     customer_id _order_date_       city product_category customer_segment  \
92     CUST00908   2025-01-22      Delhi      Electronics          Premium
422    CUST01829   2025-11-30      Delhi           Sports          Regular
535    CUST01613   2025-02-25      Delhi           Sports          Regular
567    CUST00305   2025-04-24  Bengaluru           Sports          Regular
884    CUST00421   2025-08-23     Mumbai         Clothing          Regular
1419   CUST00649   2025-08-19       Pune      Electronics          Premium
1584   CUST00800   2025-01-30       Pune           Sports          Regular
1638   CUST00381   2025-03-31  Bengaluru      Electronics          Regular
1814   CUST00011   2025-04-07      Delhi           Sports          Regular
1994   CUST00803   2025-10-15  Bengaluru           Sports          Regular

      gender sales_channel   age  units_sold  unit_price  discount_%  \
92      Male        Online  22.0        12.0     8647.35       120.0
422   Female        Retail  65.0        13.0    22779.14        75.0
535     Male     Corporate  36.0         2.0     9230.59        90.0
567   Female        Retail  35.0         5.0     8352.68       120.0
884     Male        Online  68.0         4.0    19949.75       120.0
1419  Female     Corporate  26.0         9.0     8275.94       120.0
1584    Male        Retail  21.0         8.0    16929.14        90.0
1638  Female        Retail  53.0         7.0    22605.87        75.0
1814  Female     Corporate  60.0         9.0    26935.82        90.0
1994    Male        Online  67.0         3.0    11194.48       120.0

      customer_rating is_active returned payment_method  gross_sales  \
92                3.5         1        0    Credit Card    103768.20
422               4.4         1        0            UPI    296128.82
535               4.3         1        0           Cash     18461.18
567               1.6         1        0            UPI     41763.40
884               1.7         1        1    Credit Card     79799.00
1419              2.8         1        0            UPI     74483.46
1584              2.8         0        0     Debit Card    135433.12
1638              4.5         1        1            UPI    158241.09
1814              2.3         1        1     Debit Card    242422.38
1994              4.9         0        0    Credit Card     33583.44

      discount_amount    revenue       cost    profit
92           17194.39   86573.81   57490.94  29082.87
422          63874.99  232253.83  172759.27  59494.56
535           1894.12   16567.06    8317.16   8249.90
567           9484.47   32278.93   19129.09  13149.84
884          25631.44   54167.56   41541.43  12626.13
1419         27372.67   47110.79   32512.94  14597.85
1584          1042.84  134390.28  112130.74  22259.54
1638         25255.28  132985.81   68528.62  64457.19
1814         18908.95  223513.43  169068.64  54444.79
1994          5433.80   28149.64   19955.46   8194.18
Empty DataFrame
Columns: [customer_id, _order_date_, city, product_category, customer_segment, gender, sales_channel, age, units_sold, unit_price, discount_%, customer_rating, is_active, returned, payment_method, gross_sales, discount_amount, revenue, cost, profit]
Index: []
     customer_id _order_date_       city product_category customer_segment  \
217    CUST01953   2025-12-23      Delhi           Beauty          Premium
295    CUST01326   2025-03-13  Bengaluru      Electronics          Premium
559    CUST00205   2025-10-18    Chennai      Electronics          Regular
598    CUST00458   2025-04-26  Hyderabad      Electronics          Regular
624    CUST00179   2025-04-10     Mumbai           Beauty          Premium
691    CUST01502   2025-08-22     Mumbai      Electronics          Premium
781    CUST01242   2025-09-28  Hyderabad           Sports          Premium
1007   CUST00851   2025-08-20      Delhi         Clothing          Regular
1058   CUST01854   2025-04-28     Mumbai         Clothing           Budget
1072   CUST01099   2025-03-25  Hyderabad      Electronics          Premium
1434   CUST01347   2025-07-28       Pune      Electronics          Regular
1459   CUST01700   2025-04-17     Mumbai         Clothing           Budget
1607   CUST00877   2025-12-25      Delhi   Home & Kitchen          Premium
1609   CUST01130   2025-05-29       Pune      Electronics           Budget
1810   CUST01489   2025-09-08      Delhi           Beauty          Regular

      gender sales_channel   age  units_sold  unit_price  discount_%  \
217     Male        Online  35.0       100.0     8882.86       37.62
295     Male     Corporate  26.0       200.0    29542.66       28.62
559     Male        Retail  45.0       200.0    14386.72       39.38
598   Female     Corporate  27.0       100.0    18354.17       17.15
624   Female     Corporate  42.0       100.0     6217.62       20.22
691   Female     Corporate  44.0       100.0      349.67        4.21
781     Male        Retail  43.0       200.0    18050.70       23.12
1007  Female        Retail  68.0       100.0     8867.27       16.86
1058    Male     Corporate  44.0       200.0    14353.15        2.14
1072    Male     Corporate  19.0        50.0     4755.89        0.24
1434  Female        Retail  66.0       200.0     1221.11       27.88
1459    Male     Corporate  31.0       200.0     6518.81       29.65
1607    Male        Online  64.0       200.0    21121.10       14.93
1609  Female        Retail  53.0       200.0    23160.47       26.55
1810    Male        Online  68.0        50.0    24747.44       31.45

      customer_rating is_active returned payment_method  gross_sales  \
217               4.3         1        0    Net Banking      8882.86
295               4.4         1        0     Debit Card    147713.30
559               1.4         1        1    Net Banking    100707.04
598               2.6         1        0           Cash     91770.85
624               2.6         1        0    Net Banking     62176.20
691               3.3         1        1     Debit Card       349.67
781               2.6         0        0            UPI     36101.40
1007              4.1         1        0    Credit Card     53203.62
1058              1.2         1        0     Debit Card    114825.20
1072              2.6         0        0           Cash     19023.56
1434              1.7         1        0           Cash      4884.44
1459              2.4         1        0     Debit Card     19556.43
1607              2.6         0        0    Credit Card     84484.40
1609              2.9         0        0    Credit Card    324246.58
1810              3.3         1        0    Net Banking     24747.44

      discount_amount    revenue       cost     profit
217           3341.73    5541.13    3627.22    1913.91
295          42275.55  105437.75   62356.57   43081.18
559          39658.43   61048.61   45150.83   15897.78
598          15738.70   76032.15   55826.42   20205.73
624          12572.03   49604.17   38840.76   10763.41
691             14.72     334.95     227.38     107.57
781           8346.64   27754.76   21657.35    6097.41
1007          8970.13   44233.49   32482.57   11750.92
1058          2457.26  112367.94   62882.50   49485.44
1072            45.66   18977.90   12066.65    6911.25
1434          1361.78    3522.66    2005.97    1516.69
1459          5798.48   13757.95    7649.40    6108.55
1607         12613.52   71870.88   51976.77   19894.11
1609         86087.47  238159.11  127971.37  110187.74
1810          7783.07   16964.37   12145.16    4819.21
     customer_id _order_date_       city product_category customer_segment  \
14     CUST01663   2025-04-20  Bengaluru         Clothing          Regular
315    CUST00059   2025-03-12  Bengaluru         Clothing          Regular
353    CUST01942   2025-03-22  Bengaluru           Sports          Premium
619    CUST01585   2025-09-07        NaN         Clothing          Premium
673    CUST00244   2025-01-24        NaN   Home & Kitchen          Premium
776    CUST00950   2025-09-01  Bengaluru         Clothing          Regular
812    CUST00732   2025-06-18  Hyderabad           Beauty          Regular
856    CUST01363   2025-06-22     Mumbai         Clothing           Budget
968    CUST01661   2025-04-26  Bengaluru   Home & Kitchen          Premium
1042   CUST01345   2025-04-07     Mumbai         Clothing          Regular
1153   CUST00469   2025-01-19  Bengaluru           Beauty           Budget
1188   CUST01842   2025-07-18     Mumbai           Sports          Regular
1189   CUST00546   2025-10-24       Pune           Sports          Regular
1206   CUST00979   2025-01-05     Mumbai         Clothing          Regular
1207   CUST01148   2025-09-04  Hyderabad           Sports          Premium
1307   CUST01212   2025-11-21       Pune      Electronics          Regular
1342   CUST01302   2025-11-11  Bengaluru         Clothing          Regular
1362   CUST01707   2025-05-11  Bengaluru   Home & Kitchen          Regular
1748   CUST01263   2025-06-12  Hyderabad              NaN          Regular
1918   CUST00880   2025-07-15      Delhi         Clothing          Regular
1998   CUST01870   2025-11-08  Bengaluru         Clothing          Premium
2011   CUST01872   2025-09-20      Delhi   Home & Kitchen          Regular

      gender sales_channel   age  units_sold  unit_price  discount_%  \
14      Male        Online  29.0        13.0    29280.28   12.910000
315   Female     Corporate  23.0        14.0    25767.19    5.240000
353   Female        Online  31.0        14.0    29057.39    7.300000
619     Male        Online  68.0        13.0    26955.96    0.950000
673   Female        Retail  67.0        13.0    28553.03    8.090000
776     Male     Corporate  67.0        14.0    29614.69   13.440000
812   Female     Corporate  37.0        13.0    28899.44    2.220000
856     Male        Retail  44.0        12.0    29169.92    8.690000
968     Male        Retail  69.0        14.0    29003.93   19.090000
1042    Male        Online  43.0        12.0    29665.51    1.710000
1153  Female     Corporate  21.0        14.0    26040.14    8.300000
1188    Male     Corporate  67.0        12.0    26792.17    0.200000
1189  Female        Retail  52.0        14.0    28930.36    8.760000
1206  Female        Retail  47.0        14.0    27247.79    5.570000
1207  Female        Retail  49.0        13.0    28516.09    7.470000
1307    Male     Corporate  45.0        13.0    26012.78    3.410000
1342    Male     Corporate  29.0        14.0    29357.81   16.170000
1362  Female     Corporate  44.0        14.0    26929.91   16.360000
1748    Male     Corporate  47.0        13.0    29296.82    8.950000
1918   Other        Retail  33.0        14.0    29197.34   20.897913
1998    Male        Online  19.0        14.0    26277.80   14.270000
2011    Male        Online  57.0        14.0    28160.18    0.490000

      customer_rating is_active returned payment_method  gross_sales  \
14                1.9         1        0           Cash    380643.64
315               1.5         0        1    Net Banking    360740.66
353               3.1         0        0           Cash    406803.46
619               1.2         1        1           Cash    350427.48
673               4.9         1        0           Cash    371189.39
776               4.1         1        0    Credit Card    414605.66
812               1.8         1        0    Credit Card    375692.72
856               4.0         1        0    Net Banking    350039.04
968               3.3         1        0            UPI    406055.02
1042              1.5         1        0    Credit Card    355986.12
1153              3.7         1        0            UPI    364561.96

NameError: name 'bin_cols' is not defined

In [290]:

df["Cal_profit"] = df["revenue"] -df["cost"]
df["Cal_profit"]

0       60768.140000
1       13631.370000
2        6406.000000
3       64885.041818
4        8716.970000
            ...
2015    35245.760000
2016     8693.520000
2017     6518.970000
2018    28424.800000
2019    61651.260000
Name: Cal_profit, Length: 2000, dtype: float64